resolver: lts-20.9
pvp-bounds: both
packages:
  - .
ghc-options:
  # Build with advanced optimizations enabled by default
  "$locals": -O2 -Werror
extra-deps:
  - language-javascript-0.7.0.0
  - github: wclr/purescript
    commit: 173fd7bc0147ff887d4012b51c99db60c6f3f6cb
  # Fix issue with libtinfo.
  # See https://github.com/purescript/purescript/issues/4253
  - process-1.6.13.1

  # The Cabal library is not in Stackage
  - Cabal-3.6.3.0
  # Protolude is not yet in resolver snapshot
  - protolude-0.3.1
  # hspec versions 2.9.3 to 2.10.6 depend on ghc
  # ghc depends on terminfo by default, but that can be ignored
  # if one uses the '-terminfo' flag.
  # Unfortunately, hspec doesn't expose a similar flag.
  #
  # Using hspec >= 2.10.7 addresses this.
  - hspec-2.10.9
  - hspec-core-2.10.9
  - hspec-discover-2.10.9
  
flags:
  aeson-pretty:
    lib-only: true
  these:
    assoc: false
  haskeline:
    # Avoids a libtinfo dynamic library dependency
    terminfo: false
    examples: false
  # Building on certain CentOS (maybe ghc) versions
  cryptonite:
    use_target_attributes: false